[package]
name = "state_bc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
lazy_static = "1"
byteorder = "1"
nom = "7"
nom_locate = "4"

util = {path ="../util"}